---
title: "1.6 — Deriving a Demand Function — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

*Wednesday, September 2, 2020*

# Overview

Solving a single constrained optimum problem might be useful in certain contexts, but the *dynamics* of change are more interesting: how do people optimally respond to changes in constraints? The remaining few classes before Exam 1 are about how people respond to changes in prices and income. If we can describe this set of behaviors in an equation and graphically, it is the origin of a demand curve.

Today, we look at how changes in *income* or changes in the prices of *other* goods can affect your quantity demanded for a good. 

In doing so, we also introduce a major empirical tool that we will return to many times: an *elasticity.* You've seen one elasticity before: the price elasticity of demand, and probably calculated it using the "midpoint formula." There's a lot more to elasticity (and a lot of other kinds of elasticities!) than that. We will see two varieties today, and will spend most of a lecture on price elasticity, two class periods from now.

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.6-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.6-slides.pdf)

# Practice Problems

We will start today by finishing the [practice problems](/practice/1.5-practice) (on solving the consumer’s problem) from last class. Answers will be posted on that page. Today we will be working on [practice problems](/practice/1.6-practice). Answers will be posted later on that page.

# Assignments: Problem Sets 1, 2, and Exam 1

[Problem set 1](/assignment/01-problem-set) (on 1.1-1.5) is available and is be due by 11:59 PM Sunday September 6 by PDF upload to Blackboard Assignments.

[Problem set 2]() (on classes 1.6-1.8) will also be posted shortly (it has not yet been), and will be due by 11:59 PM Sunday September 13 by PDF upload to Blackboard Assignments.

If you see on the schedule, we will quickly complete the materials needed for Exam 1. Expect it to be the week of September 14, with more details coming by early next week.