---
title: "1.8 — Price Elasticity — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

*Wednesday, September 9, 2020*

# Overview

Today we look at price elasticity of demand, and wrap up our Unit 1 on Consumer/Individual choice theory. 

A reminder, your second problem set is due next class; next class is our review session, and we will have Exam 1 on Tuesday October 1 (for Section 1 - TuTh) and Wednesday October 2 (for Section 2 - MW). See the [Exam 1 page](/assignments/01-exam) for more information and study tips.

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.7-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.7-slides.pdf)

# Practice Problems

We did not get to [1.6 practice problems](/practice/1.6-practice) (on solving income elasticity and cross-price elasticity) last class. I will cover them and go through the answers today, and answers will be posted on that page.

# Assignments: Problem Sets 1, 2, and Exam 1

The answer key to [Problem set 1](/assignment/01-problem-set) is posted to that page.

[Problem set 2](/assignment/01-problem-set) (on classes 1.6-1.8) is posted and is due by 11:59 PM Sunday September 13 by PDF upload to Blackboard Assignments.

[Exam 1](/assignment/01-exam) (on 1.1-1.8) will be next week, please read that page for much more information. We save some time for review on class Monday, September 14.


# Example Applications of Consumer Theory Models

1. [Uncertainty](/files/CT_Application_1_Uncertainty.pdf): We have examined cases where outcomes are *certain*. What if outcomes are not guaranteed, but are *uncertain* (i.e. probabilistic)? Things like your health, your investments, and the integrity of your property (from theft, natural disasters, war, etc) certainly fall into this category. For this reason, we take out *insurance* on valuable things that have some probability of significantly losing their value. Let’s explore how Consumer Theory can make our actions more intelligible.
2. [Exchange](/files/CT_Application_2_Exchange.pdf): We have examined the case of a single individual (a consumer) making optimal choices given market prices, income, and their preferences. In one sense, an economy is just a collection of millions of these individuals all doing the same thing. But economics truly begins where at the more important stage where these individuals interact and exchange *with one another.* In particular, we want to examine how relative prices and income are *determined* in an economy (up until now we simply *assumed* them as given parameters). They must come from somewhere! – the interactions of individuals buying and selling with one another, responding in order to balance supply and demand. This is where the study of (general) **equilibrium** comes from, and what the traditional Supply and Demand model captures in its simplifications.
3. [Taxation](/files/CT_Application_3_Taxation.pdf): This handout uses consumer theory to answer a simple question: **which is better for consumers, a consumption tax (tax per unit), or an equivalent income tax that raises the same amount of revenue for the government?**
4. [Intertemporal Choice (TBD)](): All of our models thus far have only looked at present consumption and ignored any element of *time.* We can also look at *intertemporal choice*, that is, consumption decisions over time. This often touches on topics that most consider "macroeconomics," concepts like interest rates, borrowing, lending, etc. However, these "big picture" ideas must come from actual individual decisions to consume or to save, aggregated across many individuals. Even macroeconomic theories often require "micro-foundations." Abstract and complex concepts like interest are actually just applications of relative price theory–interest itself is a relative price of consumption today vs. consumption in the future!
