---
title: "2.5 — Short Run Profit Maximization — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

*Wednesday, September 30, 2020*

# Overview

Today we finish up costs from [last lecture](/class/2.4-class), and briefly discuss revenues before we put them together next class to solve the firm's *profit maximization problem*. We focus on the *short run*, where the firm incurs fixed costs and must stay in the market regardless. We derive the firm's (inverse) *supply curve*.

Next class will be about the long run, and finish up unit 2. See [assignments](#assignments) below.

I have your Exam 1s graded and will discuss them at the end of class today.

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/2.5-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/2.5-slides.pdf)

# Practice Problems

Today we will be working on [practice problems](/practice/2.5-practice). Answers are posted on that page.

# Assignments


[Homework 3](assignment/03-problem-set) anawers are posted.

[Homework 4](assignment/04-problem-set) will be posted shortly, and will be due by PDF upload on Blackboard by 11:59PM Sunday October 11.

**Exam 1 corrections** are due to me by an emailed PDF by 11:59 PM Sunday October 11. You may redo any question you did not get full points on (*do not* do questions you did not lose points on), including bonuses. Write the correct answer and *explain* why it's the right answer (i.e. show your work, don't just write “It’s inelastic” when you wrote “elastic” on the exam.) I want you to demonstrate you are *internalizing* the answers and *learning*, not just comparing with your friends to get the correct answer. You can talk to each othjer now, and are welcome to come to my (and the TAs’) office hours to go over the exam together.

We will wrap up Unit 2 next Monday. We will hold a review session on Wednesday, and have **Exam 2** the following week. This time, we will *not have class on Monday October 12*, to help facilitate you taking the next exam.