---
title: "3.4 — Market Failures - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

*Monday, October 26, 2020*

# Overview

Today we continue to consider how markets work and why (and when) they are so efficient at allocating resources and solving social problems. We take a crack at defining efficiency in a few ways: [allocative](https://en.wikipedia.org/wiki/Allocative_efficiency), [productive](https://en.wikipedia.org/wiki/Productive_efficiency), [Pareto](https://en.wikipedia.org/wiki/Pareto_efficiency), and [Kaldor-Hicks](https://en.wikipedia.org/wiki/Kaldor%E2%80%93Hicks_efficiency) efficiency. We then discuss [Welfare Economics](https://en.wikipedia.org/wiki/Welfare_economics) and I summarize three conditions about when markets are good & efficient:
1. Markets are competitive
2. Markets reach equilibrium
3. Markets do not have externalities

This leads us into a discussion of [market failure](https://en.wikipedia.org/wiki/Market_failure), when markets *aren’t* efficient because something prevents the price system from working properly. We talk about several types of market failures: collective action problems, public goods, and externalities.

# Readings

See [today’s suggested readings](/reading/3.4-reading).

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/3.4-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/3.4-slides.pdf)

# Assignments: Exam 2 Corrections

Exam 2 results are on Blackboard. Please email me corrections by Sunday November 1.

