---
title: "3.5 — Government Failures & Introduction to Political Economy - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

*Monday, October 26, 2020*

# Overview

We have seen that markets can fail under a variety of circumstances, and have suggested that government intervention can improve upon the sub-optimal outcome for society. However, just because markets may fail does not mean that government cannot also fail!

We explore some examples of how governments contribute to disequilibrium and harmful outcomes by trying to intervene in markets and creating inefficiencies (through means such as price controls, taxes, and various regulations). For brevity and relevance, we focus on one set of examples: price-gouging laws and supply restrictions & regulations in the era of COVID.

We extend this to a broader discussion of the role of social, political, and economic institutions in determining outcomes. In order to fairly assess outcomes, we must examine the institutions and incentives that people face, leading to various consequences (rather than necessarily blaming the people or some behavioral motivation). We also need to avoid commiting the [“nirvana fallacy”](https://en.wikipedia.org/wiki/Nirvana_fallacy) of comparing an imperfect system we see in reality with a hypothetical perfect system we can envision. This becomes an empirical question of comparing *which systems fail the least* (or are most *robust*) in practice.

Lastly, depending on time, we may briefly explore the field of economics known as [“public choice”](https://en.wikipedia.org/wiki/Public_choice) — applying economic tools to understand politics by modelling it as equilibria determined by the interactions between various optimizing agents. 

# Readings

See [today’s suggested readings](/reading/3.5-reading).

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/3.5-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/3.5-slides.pdf)

# Assignments: Exam 2 Corrections (Due Sun Nov 1) Problem Set 5 (Due Sun Nov 8)

Exam 2 results are on Blackboard. Please email me corrections by Sunday November 1.

[Homework 5](/assignment/05-problem-set) (on 3.1-3.5) is due by PDF upload to Blackboard by 11:59 PM Sunday November 8. **This is likely your final graded homework**^[In the past, I have always released a HW 6 on Imperfect Competition just for practice for the Final Exam.]

